name = "shopify-ai-faq"
client_id = "58574156bd72a524878cc02af2bf905c"
application_url = "https://autofaq-for-products-production.up.railway.app"
embedded = true
handle = "shopify-ai-faq"

[build]
automatically_update_urls_on_dev = true
dev_store_url = "autofaq-for-products.myshopify.com"

[access_scopes]
scopes = "read_products,write_products,read_metaobjects,write_metaobjects,read_metafield_definitions,write_metafield_definitions"

[auth]
redirect_urls = [
  "https://autofaq-for-products-production.up.railway.app/auth/callback",
  "https://autofaq-for-products-production.up.railway.app/auth/shopify/callback",
  "https://autofaq-for-products-production.up.railway.app/api/auth/callback",
  "https://autofaq-for-products-production.up.railway.app/app/billing/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = ["app/uninstalled"]
  uri = "/webhooks"

  [[webhooks.subscriptions]]
  topics = ["products/update"]
  uri = "/webhooks/products-update"
[[webhooks.subscriptions]]
topics = ["customers/data_request"]
uri = "/webhooks"

[[webhooks.subscriptions]]
topics = ["customers/redact"]
uri = "/webhooks"

[[webhooks.subscriptions]]
topics = ["shop/redact"]
uri = "/webhooks"

[pos]
embedded = false
