name = "AI FAQ Section"
uid = "5e17ca68-fa05-7297-eec3-b906e7223edeefbb427c"
type = "theme"
handle = "ai-faq-extension"

[[extensions]]
type = "theme"
name = "AI FAQ Section"
handle = "ai-faq-extension"
